# Generated by Django 4.2.3 on 2023-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='startingbid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
