# Generated by Django 4.2.3 on 2023-07-17 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_price_comments_comments_listings_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='price',
            new_name='bidprice',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.ManyToManyField(to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='commentsby',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listings',
            name='listedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='wathlist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won', to=settings.AUTH_USER_MODEL),
        ),
    ]
