# Generated by Django 4.2.3 on 2023-07-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_category_alter_listings_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='startingbid',
            new_name='bidprice',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='bidprice',
        ),
    ]
