# Generated by Django 4.2.3 on 2023-07-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_startingbid_listings_bidprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
