# Generated by Django 4.2.3 on 2023-07-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listings_listedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bidprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
