# Generated by Django 4.2.3 on 2023-07-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listings_bidprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='wathlist',
            new_name='watchlist',
        ),
    ]
