# Generated by Django 4.2.3 on 2023-07-21 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_wathlist_listings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
