# Generated by Django 4.2.3 on 2023-07-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listings_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='bidlisting',
            field=models.ManyToManyField(related_name='bids', to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidplaced',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
