# Generated by Django 4.2.3 on 2023-07-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_bids_bid_bids_bidlisting_bids_bidplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bidlisting',
        ),
        migrations.AddField(
            model_name='bids',
            name='bidlisting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidslist', to='auctions.listings'),
        ),
    ]
