# Generated by Django 4.2.3 on 2023-07-22 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_bidprice_listings_startingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentlist',
            field=models.ManyToManyField(related_name='commented_on', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentsby',
            field=models.ManyToManyField(related_name='commented_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
