# Generated by Django 4.2.3 on 2023-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comments_commentlist_alter_comments_commentsby'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commenttime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
