# Generated by Django 4.2.3 on 2023-07-25 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_comments_commenttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commentsby',
        ),
        migrations.AddField(
            model_name='comments',
            name='commentsby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
